### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Neospiro** [mtxr/SQLTools#1]
seems you have the same problem I corrected here
https://github.com/Neospiro/sublime-sqlexec/commit/8377b3e37b97e1c814a7cdb024708d6365ef3cfb

There is a known bug with python subprocess implement on windows, when you don't specify default value stdin, it doesn't work.

The original call in SQLExec doesn't specify default stdin : 
`results, errors = subprocess.Popen(self.text, stdout=subprocess.PIPE,stderr=subprocess.PIPE, shell=True).communicate()`
if you don't add `stdin=subprocess.DEVNULL` there is a bug and Popen will make error

```
Traceback (most recent call last):
  File "E:\Applications portables\ST3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "SQLExec in E:\Applications portables\ST3\Data\Installed Packages\SQLExec.sublime-package", line 212, in run
  File "SQLExec in E:\Applications portables\ST3\Data\Installed Packages\SQLExec.sublime-package", line 30, in execute
  File "SQLExec in E:\Applications portables\ST3\Data\Installed Packages\SQLExec.sublime-package", line 94, in show
  File "SQLExec in E:\Applications portables\ST3\Data\Installed Packages\SQLExec.sublime-package", line 86, in run
  File "./subprocess.py", line 789, in __init__
  File "./subprocess.py", line 988, in _get_handles
  File "./subprocess.py", line 1038, in _make_inheritable
OSError: [WinError 6] Descripteur non valide
```

EDIT : I tried to patch it myself but I don't know very well python and I can't make it work :disappointed: .
```
Traceback (most recent call last):
  File "SQLTools in E:\Applications portables\ST3\Data\Installed Packages\SQLTools.sublime-package", line 26, in sqlChangeConnection
  File "E:\Applications portables\ST3\Data\Installed Packages\SQLTools.sublime-package\lib\connection.py", line 61, in desc
  File "E:\Applications portables\ST3\Data\Installed Packages\SQLTools.sublime-package\lib\command.py", line 37, in execute
AttributeError: 'module' object has no attribute 'setsid'
```

Please check out
I come back to SQLExec for today :crying_cat_face: 

sorry for my bad english
Love from France

**Comment by mtxr** [comment]
I'm on it. Seems to be a problem when trying to kill query process.

I'm probably fixing it till the end of the day.

Thanks ;)

**Comment by mtxr** [comment]
@Neospiro, What's your sublime version? 3103?

**Comment by Neospiro** [comment]
yes

**Comment by mtxr** [comment]
Coould you please try this pre-realease?
https://github.com/mtxr/SQLTools/releases/tag/v0.0.2

**Comment by mtxr** [comment]
It's working, just tested on windows
