### ISSUE TITLE
NameError: global name 'Window' is not defined

### ISSUE THREAD

**Issue by fvelcker** [mtxr/SQLTools#10]
Hey, 

Thanks for the today's fix, but I got this now:

```
Traceback (most recent call last):
  File "C:\cmder\vendor\Sublime Text 3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 172, in run
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 73, in showConnectionMenu
NameError: global name 'Window' is not defined
```

**Comment by mtxr** [comment]
Just reme the package and installs again. I forgot some vars without change

**Comment by mtxr** [comment]
Did it work?

**Comment by fvelcker** [comment]
Yep, but i have this one when I execute the query :-)

```
Traceback (most recent call last):
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 58, in setConnection
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 46, in loadConnectionData
  File "C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 141, in getTables
  File "C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 199, in builArgs
AttributeError: 'list' object has no attribute 'format'
```

**Comment by mtxr** [comment]
Probably it was a problem during the reload after updated.

Could you send me more details?
You connections settings and user settings as well would help me a lot.

Before it just try to use v0.1.7 and see if it still happening.

**Comment by fvelcker** [comment]
Hello,

Nope not working but an error message a bit different different error:
```
Traceback (most recent call last):
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 58, in setConnection
  File "SQLTools in C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package", line 46, in loadConnectionData
  File "C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 141, in getTables
  File "C:\cmder\vendor\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 199, in builArgs
AttributeError: 'list' object has no attribute 'format'
```
It happens at the selection on the connection.

My SQLTools user settings are empty and there is the connection settings:
```
{
    "connections": {
        "Dev": {
            "type"    : "mysql",
            "host"    : "xxx.xxx.xxx.xxx",
            "port"    : 3306,
            "username": "cakeuser",
            "password": "xxxxxxxxx",
            "database": "cake"
        }
    },
    "default": "Dev"
}
```
(Sorry, I would have any skills in python and sublime plugin dev, I would have a look at it by myself, but I don't know anything about them... though it could be the occasion to learn :-))

**Comment by mtxr** [comment]
Could you post your SQLtools user settings too?

**Comment by fvelcker** [comment]
That's what I said in my previous post, there are empty, I am using the default ones.

**Comment by mtxr** [comment]
Okay. Thanks!

**Comment by fvelcker** [comment]
But let me know if you want me to try with some users specific settings.

**Comment by mtxr** [comment]
Just updated project logging version and something close to the failed line.

Wait till v0.1.8 shows up here (https://packagecontrol.io/packages/SQLTools), close your ST and opens it again.

Press "CTRL+SHIFT+P"
Find "Package Control: Upgrade package"
Select "SQLTools" and wait.

It must work, if it stills failing, get your ST console messages and send to me again please :D


Thanks!
