### ISSUE TITLE
Error after update plugin

### ISSUE THREAD

**Issue by victoreduardobarreto** [mtxr/SQLTools#111]
Arrived a new version of plugin, after I had this error.

Traceback (most recent call last):
  File "/home/victorbarreto/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 278, in <lambda>
    Window().show_quick_panel(menu, lambda index: ST.setConnection(index, tablesCallback, columnsCallback, functionsCallback))
  File "/home/victorbarreto/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 263, in setConnection
    ST.loadConnectionData(tablesCallback, columnsCallback, functionsCallback)
  File "/home/victorbarreto/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 246, in loadConnectionData
    ST.conn.getTables(tbCallback)
  File "/home/victorbarreto/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 81, in getTables
    env = self.buildEnv()
TypeError: createAndRun() missing 1 required positional argument: 'callback'

**Comment by tkopets** [comment]
This issue got resolved after Sublime Text restart?
