### ISSUE TITLE
SQLTools unable to execute

### ISSUE THREAD

**Issue by markljackson** [mtxr/SQLTools#123]
### Issue Type

* [ ] Feature Request
* [ ] Bugfix/Errors
* [ ] Questions
* [X] Other

### Prerequisites (For bugfixes)

* [X] Are you running the latest version?
* [X] Did you check the logs?
* [X] Did you check the Setup?

### Description

No matter how I try to activate SQLTools database commands, I get nothing. When I checked the console I found this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 469, in run
    ST.selectConnection(tablesCallback=lambda: Window().run_command('st_execute'))
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 269, in selectConnection
    ST.connectionList = getConnections()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 79, in getConnections
    startPlugin()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 62, in startPlugin
    connections = Settings(CONNECTIONS_FILENAME, default=CONNECTIONS_FILENAME_DEFAULT)
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLToolsAPI/Storage.py", line 18, in __init__
    self.all()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLToolsAPI/Storage.py", line 21, in all
    self.items = U.parseJson(self.getFilename())
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLToolsAPI/Utils.py", line 47, in parseJson
    return json.loads(content, encoding='utf-8')
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting object: line 19 column 2 (char 261)
```

I am able to bring up the settings panels, but not able to connect to the database, or run a query..

NOTE: I was able to set up _SQLExec_, and that works fine.

### Steps to Reproduce (For bugfixes)

1. open COMMAND PALETTE
2. type in ST: 
3. try to execute any database command

**Expected behavior:** [What you expected to happen]

I expected to be able to connect to mysql, and run a query.

**Actual behavior:** [What actually happened]

Nothing. I had to look in the console to see what was happening.

### Versions

- *Version*: v0.9.4
- *OS*: OSX Sierra
- *RDBMS*: MySQL

**Comment by tkopets** [comment]
Most probably you have some kind of problem in `SQLToolsConnections.sublime-settings`, could be invalid json ?

Can you post your entire connections json file?

**Comment by markljackson** [comment]
I've redacted the password. It has a "0", and "!" in it; the rest are letters, two caps.

```
{
  "connections": {
    "bank": {
      "type"    : "mysql",
      "host"    : "127.0.0.1",
      "port"    :  3306,
      "database": "bank",
      "username": "lrnsql",
      // use of password for MySQL is not recommended (use "defaults-extra-file" or "login-path")
      "password": "redacted",  // you will get a security warning in the output
      // "defaults-extra-file": "/path/to/defaults_file_with_password",  // use [client] or [mysql] section
      // "login-path": "your_login_path",  
      // login path in your ".mylogin.cnf"
      "encoding": "utf-8"
  },
  // "default": "bank"
 "default" : null
}
```

**Comment by tkopets** [comment]
You have missing one closing `{` bracket (3 open curly brackets and only 2 closing).

**Comment by tkopets** [comment]
You have missing one closing `}` bracket (3 open curly brackets and only 2 closing).

**Comment by tkopets** [comment]
```
{
  "connections": {
    "bank": {
      "type"    : "mysql",
      "host"    : "127.0.0.1",
      "port"    :  3306,
      "database": "bank",
      "username": "lrnsql",
      // use of password for MySQL is not recommended (use "defaults-extra-file" or "login-path")
      "password": "redacted",  // you will get a security warning in the output
      // "defaults-extra-file": "/path/to/defaults_file_with_password",  // use [client] or [mysql] section
      // "login-path": "your_login_path",  
      // login path in your ".mylogin.cnf"
      "encoding": "utf-8"
  },
  // "default": "bank"
 "default" : null
}
}
```

**Comment by markljackson** [comment]
Ok, I set that up correctly, but now I'm getting this:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 469, in run
    ST.selectConnection(tablesCallback=lambda: Window().run_command('st_execute'))
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 269, in selectConnection
    ST.connectionList = getConnections()
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 84, in getConnections
    connectionsObj[name] = createConnection(name, config, settings=settings.all())
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 101, in createConnection
    newConnection = Connection(name, config, settings=settings)
  File "/Users/-USERNAME-/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 48, in __init__
    self.type       = options.get('type', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

Do I need to specify the path to MYSQL? Or am I missing something else?

**Comment by tkopets** [comment]
Mark,
I was on mobile and couldn't test my suggestion.
I made a mistake and put the brace in wrong place.
I've double checked and this one should work for you:

```
{
  "connections": {
    "bank": {
      "type"    : "mysql",
      "host"    : "127.0.0.1",
      "port"    :  3306,
      "database": "bank",
      "username": "lrnsql",
      // use of password for MySQL is not recommended (use "defaults-extra-file" or "login-path")
      "password": "redacted",  // you will get a security warning in the output
      // "defaults-extra-file": "/path/to/defaults_file_with_password",  // use [client] or [mysql] section
      // "login-path": "your_login_path",  
      // login path in your ".mylogin.cnf"
      "encoding": "utf-8"
    }
  },
  "default": "bank"
}
```

**Comment by markljackson** [comment]
That worked, thanks.
