### ISSUE TITLE
SQLTools not functioning after update of ST3

### ISSUE THREAD

**Issue by markljackson** [mtxr/SQLTools#198]
### Issue Type

commands will not run. I've tried CTRL+e,e. I've also tried the command palette. No joy.

I can get to the settings through command palette, but no actions are accessible.

** Bug/Error **

### Description

When I try to run code with CTRL+e,e nothing happens.

### Version

- *SQLTools Version*: v0.9.9
- *OS*: Mac
- *RDBMS*: MySQL

### Steps to Reproduce (For bugfixes)

1.  enter code in editor
2. highlight code
3. press CTRL + e, e

**Expected behavior:** [What you expected to happen]

Code to run against MySQL database.

**Actual behavior:** [What actually happened]

Nothing happens. I've tried all of the commands that act on the database, and nothing happens.

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1036, in run_
    return self.run()
  File "/Users/MY_USER_NAME/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 559, in run
    ST.selectConnection(tablesCallback=lambda: Window().run_command('st_execute'))
  File "/Users/MY_USER_NAME/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 359, in selectConnection
    ST.connectionList = getConnections()
  File "/Users/MY_USER_NAME/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 96, in getConnections
    connectionsObj[name] = createConnection(name, config, settings=settings.all())
AttributeError: 'NoneType' object has no attribute 'all'

**Comment by tkopets** [comment]
Hello Mark!
Thank you for reporting this issue.
Can you provide a bit more info on your issue:
Please review the entire Sublime Console history to see if there are any other errors before the one you posted?
Is there any chance you have modified the SQLTools settings recently and SQLTools fails to parse the settings file (e.g. not a valid JSON anymore)?
Or it worked fine before the update and just stopped working after Sublime update?

My Sublime just updated to v. 3170 on Mac and looks fine, so I assume this issue is specific to your environment.

**Comment by markljackson** [comment]
It appears that some Python settings were pasted into the SQLTools user settings. Took the out, and all seems well.

Thanks
