### ISSUE TITLE
No results, weird error in OSX.

### ISSUE THREAD

**Issue by leemm** [mtxr/SQLTools#21]
Hi, I'm really having problems getting this working with my local mysql install.

This is the process I took from a clean install:
- Installed via package manager
- Set up connection
- Created a script and Executed

Result? Nothing at all apart from the standard mysql 'cleartext password' message.

At first I thought it was the query so I ran it in Sequel Pro and it worked fine, so I attempted to strip it back to the very basics.  Still nothing... so I tried show tables;  still nothing.

Looking in the console I can see the connection:

`SQLTools v0.3.1: Usgin cli args /usr/local/mysql/bin/mysql -f --table -h192.168.10.10 -P3306 -u***** -p***** -Dtest_db`

Running this command via terminal works fine, as does show tables; once connected.

I then noticed a strange message in the trace:

Traceback (most recent call last):
  ```
File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "SQLTools in /Users/macusr/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 84, in on_query_completions
  File "SQLTools in /Users/macusr/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 102, in getAutoCompleteList
AttributeError: type object 'ST' has no attribute 'functions'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "SQLTools in /Users/macusr/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 84, in on_query_completions
  File "SQLTools in /Users/macusr/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 102, in getAutoCompleteList
AttributeError: type object 'ST' has no attribute 'functions'
```

I assume this is the problem but where do I go from here?

Thanks!

**Comment by mtxr** [comment]
Hello! thanks!

It seems to be simple. I will fix that ok?
