### ISSUE TITLE
FileNotFoundError when executing SQL

### ISSUE THREAD

**Issue by nymo** [mtxr/SQLTools#26]
I did a clean install with version v0.3.1. I configured my connections like described in the documentation.
When I do a "Select connections" I receive the following error in the console:

`Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\dev\Sublime Text 3\Data\Installed Packages\SQLTools.sublime-package\SQLToolsModels.py", line 271, in run
    self.process = subprocess.Popen(self.args, stdout=subprocess.PIPE,stderr=subprocess.PIPE, stdin=open(self.tmp.name), env=os.environ.copy(), startupinfo=si)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2]`

I can't execute any queries.

**Comment by shakticha** [comment]
I encountered similar issue on my mac installation. While command "Select Connection" seem to work, all other commands fail throwing the following exception in the console.

`Exception in thread Thread-63:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/Diva/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package/SQLToolsModels.py", line 271, in run
    self.process = subprocess.Popen(self.args, stdout=subprocess.PIPE,stderr=subprocess.PIPE, stdin=open(self.tmp.name), env=os.environ.copy(), startupinfo=si)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'mysql'`

**Comment by mtxr** [comment]
The problem is SQLTools couldn't find you **mysql** cli file path.

Try to set it manually in your SQLTools.sublime-settings. Check the docs: [](http://code.mteixeira.me/SQLTools/#settings)

``` json
    "cli" : {
        "mysql"   : "/usr/bin/mysql",
        ...
    },
```
