### ISSUE TITLE
SQLite setup

### ISSUE THREAD

**Issue by daftscience** [mtxr/SQLTools#31]
Do you have an example for an SQL Connection?

I'm getting this message when I try my configuration

```
Traceback (most recent call last):
  File "C:\Users\Tom\Desktop\Sublime Dev\Data\Packages\SQLTools\SQLTools.py", line 60, in setConnection
    ST.loadConnectionData()
  File "C:\Users\Tom\Desktop\Sublime Dev\Data\Packages\SQLTools\SQLTools.py", line 47, in loadConnectionData
    ST.conn.getTables(lambda tables: ST.setAttrIfNotEmpty('tables', tables))
  File "C:\Users\Tom\Desktop\Sublime Dev\Data\Packages\SQLTools\SQLToolsModels.py", line 153, in getTables
    self.runCommand(self.builArgs('desc'), query, lambda result: Utils.getResultAsList(result, callback))
  File "C:\Users\Tom\Desktop\Sublime Dev\Data\Packages\SQLTools\SQLToolsModels.py", line 228, in builArgs
    Log.debug('Usgin cli args ' + ' '.join(args + shlex.split(cliOptions['args'].format(**self.options))))
KeyError: 'options'
```

Update:

I've played around with the source code a bit, and made some changes to both the code and query. 

Changing this function in SQLToolsModels.py to use ```.format``` and updating the table descriptions query seems to have helped.
```python
def getTableDescription(self, tableName, callback):
        query   = self.getOptionsForSgdbCli()['queries']['desc table']['query'] % tableName
        self.runCommand(self.builArgs('desc table'), query, lambda result: callback(result))
```
To:
```python
def getTableDescription(self, tableName, callback):
        query = self.getOptionsForSgdbCli()['queries']['desc table']['query'].format(tableName)
        self.runCommand(self.builArgs('desc table'), query, lambda result: callback(result))
```

For the SQLTools settings, I had to update the ```queries```, ```args```, ```options```
```javascript
{
    "show_result_on_window" : true,
    "cli_options": {
        "sqlite": {
            "options": ["-column"],
            "before": [".headers on"],
            "args": "{database}",
            "queries": {
                "desc" : {
                    "query": ".headers off\nSELECT '|' || name || '|' FROM sqlite_master WHERE type='table';",
                    "options": [],
                    "format" : "|%s|"
                    },
                "desc table": {
                    "query": "pragma table_info({});",
                    "options": ["-column"],
                    "format" : "%s"
                    },
                "show records": {
                    "query": "select * from {} limit 100;",
                    "options": ["-column"],
                    "format" : "|%s|"
                }
            }
        }
    }
}

```

**Comment by mtxr** [comment]
Thanks mate! Could you send a pull request?

**Comment by mtxr** [comment]
The new version fixed it. Closing
