### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by mabdelfattah** [mtxr/SQLTools#39]
I setup my connections but each time I try to use any command, I get the following error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "SQLTools in /Users/mahmoud/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 314, in run
  File "SQLTools in /Users/mahmoud/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 200, in selectConnection
  File "SQLTools in /Users/mahmoud/Library/Application Support/Sublime Text 3/Installed Packages/SQLTools.sublime-package", line 59, in getConnections
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mtxr** [comment]
Fixing.

**Comment by mtxr** [comment]
Try the new version please

**Comment by mabdelfattah** [comment]
`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/mahmoud/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 292, in run
    ST.selectConnection()
  File "/Users/mahmoud/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 200, in selectConnection
    ST.connectionList = getConnections()
  File "/Users/mahmoud/Library/Application Support/Sublime Text 3/Packages/SQLTools/SQLTools.py", line 59, in getConnections
    options = connections.get('connections', {})
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by gc-alexlong** [comment]
I, too, get that same error, and the currently installed version is 0.6.4.
MacOS 10.11.6
Sublime Text build 3126

**Comment by XONOSNET** [comment]
Traceback (most recent call last):
  File "C:\Users\twood\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 217, in <lambda>
    Window().show_quick_panel(menu, lambda index: ST.setConnection(index, tablesCallback, columnsCallback, functionsCallback))
  File "C:\Users\twood\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 202, in setConnection
    ST.loadConnectionData(tablesCallback, columnsCallback, functionsCallback)
  File "C:\Users\twood\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 189, in loadConnectionData
    ST.conn.getTables(tbCallback)
  File "C:\Users\twood\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsAPI\Connection.py", line 63, in getTables
    query = self.getOptionsForSgdbCli()['queries']['desc']['query']
  File "C:\Users\twood\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsAPI\Connection.py", line 159, in getOptionsForSgdbCli
    return self.settings.get('cli_options', {}).get(self.type)
AttributeError: 'NoneType' object has no attribute 'get'

As of 1/30/2017 - Getting this error with latest version.
