### ISSUE TITLE
'Connection' object has no attribute 'name'

### ISSUE THREAD

**Issue by DrStannum** [mtxr/SQLTools#41]
**OS**: Windows 10
**ST**:  Sublime Text 3, Build 3126

**Console**:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 292, in run
    ST.selectConnection()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 207, in selectConnection
    menu.append([conn.name, conn._info()])
AttributeError: 'Connection' object has no attribute 'name'

```

Connections file: 
```
{
	"connections": {
		"database@localhost": {
			"type"    : "mysql",
			"host"    : "127.0.0.1",
			"port"    : 3306,
			"username": "login",
			"password": "password",
			"database": "database",
			"encoding": "utf-8"
		}
	},
	"default": "database@localhost"
}
```

**Comment by vegatron** [comment]
I'm having the same issue, I'm also using Windows 10 / Sublime Text 3 Build 3126

**Comment by geonicz** [comment]
Same issue, same environment except for Windows 7 x64.

**Comment by 441211324** [comment]
我也发现同样的问题！windows x64 @mtxr

**Comment by mtxr** [comment]
I'll be fixing it this weekend. Sorry guys!

**Comment by Demetrio92** [comment]
Thanks for your work @mtxr, keep the project alive!

I suggest you start by looking at the line 
`connectionsObj[name] = Connection(name, config, settings=settings.all())`
in the `getConnections`.
It has troubles getting the `name`, which I guess is due to a conflict in the namespace. 
In any case, you can test it by using my `SQLToolsConnections.sublime-settings` file from the issue #41 (don't forget to remove the incorrect trailing comma there).

**Comment by mtxr** [comment]
Fixed on last commit

**Comment by prozacsf84** [comment]
@mtxr same here - windows 10 . SQLTools 0.6.6

<pre>
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLTools.py", line 354, in run
    ST.conn.execute(getSelection(), output)
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsAPI\Connection.py", line 104, in execute
    for query in self.getOptionsForSgdbCli()['before']:
  File "C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\SQLTools\SQLToolsAPI\Connection.py", line 142, in getOptionsForSgdbCli
    return self.settings.get('cli_options', {}).get(self.type)
AttributeError: 'NoneType' object has no attribute 'get'
</pre>
