### ISSUE TITLE
Error when the connection file ending with comma

### ISSUE THREAD

**Issue by evandrocoan** [mtxr/SQLTools#44]
### Error when the connection file ending with comma

Sublime Text JSON files accept this:
```
{
    "connections": 
    {
        "Postgres Aula 20": 
        {
            "type"    : "pgsql",
            "host"    : "127.0.0.1",
        },
    },
    "default": "Postgres Aula 20",
},
```
But with this package, it only accept trailing the last comma:
```
{
    "connections": 
    {
        "Postgres Aula 20": 
        {
            "type"    : "pgsql",
            "host"    : "127.0.0.1",
        }
    }
    "default": "Postgres Aula 20"
},
```

This the stack trace, on the connections file:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 797, in run_
    return self.run()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 292, in run
    ST.selectConnection()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 200, in selectConnection
    ST.connectionList = getConnections()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 59, in getConnections
    options = connections.get('connections', {})
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLToolsAPI\Storage.py", line 50, in get
    items = self.all()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLToolsAPI\Storage.py", line 19, in all
    self.items = U.parseJson(self.getFilename())
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLToolsAPI\Utils.py", line 43, in parseJson
    return json.loads(content, encoding='utf-8')
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 367, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 17 column 1 (char 360)
```

**Comment by Demetrio92** [comment]
This is a py error, not SQLTools error. You should not use trailing commas in your .sublime-settings files. You do this, b/c sublime has their own sublime_api.read_settings, which allows trailing commas. 

A suggestion to @mtxr  would be to maybe switch from json.loads to sublime_api.read_settings

**Comment by mtxr** [comment]
I'll be fixing it this weekend. Sorry guys!

**Comment by evandrocoan** [comment]
Thanks! Good and clever work.
