### ISSUE TITLE
TypeError: 'NoneType' object is not iterable, on auto completion

### ISSUE THREAD

**Issue by evandrocoan** [mtxr/SQLTools#45]
### TypeError: 'NoneType' object is not iterable, on auto completion

This keeps popping on my console:
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 243, in on_query_completions
    return completions + ST.getAutoCompleteList(prefix)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 249, in getAutoCompleteList
    for w in ST.tables:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 243, in on_query_completions
    return completions + ST.getAutoCompleteList(prefix)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 249, in getAutoCompleteList
    for w in ST.tables:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 243, in on_query_completions
    return completions + ST.getAutoCompleteList(prefix)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 249, in getAutoCompleteList
    for w in ST.tables:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 243, in on_query_completions
    return completions + ST.getAutoCompleteList(prefix)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\SQLTools\SQLTools.py", line 249, in getAutoCompleteList
    for w in ST.tables:
TypeError: 'NoneType' object is not iterable
```

**Comment by mtxr** [comment]
I'll be fixing it this weekend. Sorry guys!
