### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by facsa79** [mtxr/SQLTools#48]
Debian Jessie, Sublime Text 3, SQLTools v0.6.6
MySQL server is on a remote host in my LAN (192.168.1.1:3306)

connection settings:
```
{
    "connections": {
        "Connection 1": {
            "type"    : "mysql",
            "host"    : "192.168.1.1",
            "port"    : 3306,
            "username": "demo_adm",
            "password": "demo_password",
            "database": "demo_database",
            "encoding": "utf-8"
        },
        "Connection 2": {
            "type"    : "pgsql",
            "host"    : "127.0.0.1",
            "port"    :  5432,
            "username": "anotheruser",
            "database": "dbname",
            "encoding": "utf-8"
        },
        "Connection 3": {
            "type"    : "oracle",
            "host"    : "127.0.0.1",
            "port"    :  1522,
            "username": "anotheruser",
            "password": "password",
            "database": "dbname",
            "service" : "servicename",
            "encoding": "utf-8"
        }
    },
    "default": "Connection 1"
}
```
ST: Select Connection --> selecting first one
```
Traceback (most recent call last):
  File "/home/facsa/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 213, in <lambda>
    Window().show_quick_panel(menu, lambda index: ST.setConnection(index, tablesCallback, columnsCallback, functionsCallback))
  File "/home/facsa/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 198, in setConnection
    ST.loadConnectionData(tablesCallback, columnsCallback, functionsCallback)
  File "/home/facsa/.config/sublime-text-3/Packages/SQLTools/SQLTools.py", line 185, in loadConnectionData
    ST.conn.getTables(tbCallback)
  File "/home/facsa/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 58, in getTables
    query = self.getOptionsForSgdbCli()['queries']['desc']['query']
  File "/home/facsa/.config/sublime-text-3/Packages/SQLTools/SQLToolsAPI/Connection.py", line 142, in getOptionsForSgdbCli
    return self.settings.get('cli_options', {}).get(self.type)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by 441211324** [comment]
I met the same mistake, but I debug it.

**Comment by mtxr** [comment]
Could you send your settings file? ST: Settings on menu

**Comment by 441211324** [comment]
**Preferences.sublime-settings**
```
"auto_complete_triggers":
[
    {
        "characters": "<",
        "selector": "text.html"
    },
    {
        "characters": ".",
        "selector": "source.sql"
    }
],
```
Preterences\Package Setttings\SQLTools\Connections - User
**Data\Packages\User\SQLToolsConnections.sublime-settings**

```
{
    "connections": {
        "database@localhost": {
            "type"    : "mysql",
            "host"    : "127.0.0.1",
            "port"    : 3306,
            "username": "root",
            "password": "root",
            "database": "74job",
            "encoding": "utf-8",
        }
    },
    "default": "database@localhost"
}
```


**Data\Packages\User\SQLTools\SQLToolsConnections.sublime-settings**

```
{
    "connections": {
        "database@localhost": {
            "type"    : "mysql",
            "host"    : "127.0.0.1",
            "port"    : 3306,
            "username": "root",
            "password": "root",
            "database": "74job",
            "encoding": "utf-8",
        }
    },
    "default": "database@localhost"
}
```

**Comment by 441211324** [comment]
Packages/User/SQLToolsConnections.sublime-settings

```
{
    "connections": {
        "database@localhost": {
            "type"    : "mysql",
            "host"    : "127.0.0.1",
            "port"    : 3306,
            "username": "root",
            "password": "root",
            "database": "74job",
            "encoding": "utf-8",
        }
    },
    "default": "database@localhost"
}


```
Packages/SQLTools/SQLToolsConnections.sublime-settings

```

{
    "connections": {

        "feiji": {         // Connection name, used in menu (Display name)
            "database" : "74job",
            "host"     : "127.0.0.1",
            "port"     : "3306",
            "type"     : "mysql",    // SGDB to use: (mysql, pgsql, oracle, vertica)
            "username" : "root",
            "password" : "root",        // (if you are using postgresql, you must setup a pgpass file and set it to null)
            "encoding" : "utf-8"        // Your DB encodings. Default: utf-8
        }

    },
    "default": "feiji"
}
```





ctrl+e,d 

database@localhost
DB:None,Connection:None@None:None

feiji
DB:None,Connection:None@None:None

**Comment by drafu** [comment]
Had the same issues.
Debugged SQLTools.py to the core.
The issue is in missing postgresql client
Resolved by installing `postgresql-client-common` and `postgresql-client-9.5`

**Comment by 441211324** [comment]
In China MySQL popular, is the first time I heard about PostgreSQL, 
What do I do? I need to install a PostgreSQL to continue to use SQLTools?

**Comment by drafu** [comment]
Maybe you just need to install client of your own db, I'm not really sure. 
As long as I use PostgreSQL, I needed to install postgresql client for this exact error to disappear

**Comment by mtxr** [comment]
hey @441211324,

If you are on a remote server, you should install mysql-cli on your computer.
I'm assuming you are using a debian based distro, so try this:
`sudo apt-get install mysql-client`

Then you should be able to connect your remote host from you terminal using mysql-cli.

If it works, SQLTools will work too, ok?

**Comment by facsa79** [comment]
I wrongly assumed that SQLTools installs all dependent files.
It's logical if the SQL server lies on a remote host, the appropriate SQL client must to be installed to the same machine as the superb ST.
After manual installation the client `sudo apt-get install mysql-client` all works fine.
Thank you
